### ISSUE TITLE
EN_TANKDIAM  - 17 Tank diameter 

### ISSUE THREAD

**Issue by jonas1790** [OpenWaterAnalytics/epanet-matlab#3]
Calling Engetnodevalue with parameter 17 gives me for all my tanks a wrong output. The values are approx. 1.13 higher than the original value typed in into epanet. Do you have the same issue? (units = m)

**Comment by samhatchett** [comment]
I'm thinking this is related to a bug in epanet -- look at https://github.com/yuniersoad/epanet/commit/1ff4266a4f14271c8089537398e702dad45f5556 

will leave this open until the fix can be confirmed in MatLab.

**Comment by jonas1790** [comment]
Thanks :)
