### ISSUE TITLE
Error with epanetmsx library

### ISSUE THREAD

**Issue by lovelesh** [OpenWaterAnalytics/epanet-matlab#4]
Hi,

I ma having problems while running the example.m file.
I have copied "epanet2.dll", "epanet2.h", epanetmsx.dll", "epanetmsx.h" in my current working directory. epanet2.dll is loading correctly but this is the error I am getting when it tries to load epanetmsx.dll.

??? Error using ==> loadlibrary at 477
There was an error loading the library "epanetmsx"
epanetmsx.so: cannot open shared object file: No such file or directory

Thanks

**Comment by jamesuber** [comment]
What platform are you working on?

You seem to be working on Linux, based on the matlab complaint that it can’t find ‘epanetmsx.so’. Yet you state you are using a dynamic link library (DLL), which wouldn’t have any place on a Linux system.

-Jim

 http://www.citilogics.com/ JIM UBER mailto:jim@citilogics.com • 513.368.6303 tel:513-368-6303 • CITILOGICS.COM http://www.citilogics.com/
